testing/urls.py
from django.urls import path

from testing.views import themes, tests, questions, results

app_name = 'testing'

urlpatterns = [
    path('', themes, name='themes'),
    path('<int:theme_pk>/tests', tests, name='tests'),
    path('<int:theme_pk>/tests/<int:test_pk>', questions, name='questions'),
    path('<int:theme_pk>/tests/<int:test_pk>/questions/<int:page>', questions, name='page'),
    path('<int:theme_pk>/tests/<int:test_pk>/results', results, name='results')
]

testing_service/urls.py
from django.contrib import admin
from django.urls import path, include

from testing.views import home, signup, login, logout

urlpatterns = [
    path('admin/', admin.site.urls),

    # Auth
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),

    path('', home, name='home'),
    path('themes/', include('testing.urls', namespace='testing'))
]

testing/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Theme(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()

    def __str__(self):
        return self.title


class Test_single(models.Model):
    title = models.CharField(max_length=350)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Question(models.Model):
    title = models.CharField(max_length=1000)
    test = models.ForeignKey(Test_single, on_delete=models.CASCADE)
    max_points = models.FloatField()

    def __str__(self):
        return self.title


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    title = models.CharField(max_length=1000)
    points = models.FloatField()

    def __str__(self):
        return self.title


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    test = models.ForeignKey(Test_single, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} | {self.question}'


class Results(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    test = models.ForeignKey(Test_single, on_delete=models.CASCADE)
    sum_points = models.FloatField()

    def __str__(self):
        return f'{self.user} | {self.test}'

testing/forms.py
from django.forms import ModelForm
from .models import Answer


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['choice']

testing/views.py
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from testing.forms import AnswerForm
from testing.models import Theme, Test_single, Question, Choice, Answer, Results


def home(request):
    context = {
        'title': 'Home'
    }
    return render(request, 'testing/home.html', context)


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Вы успешно зарегестрировались!')
            auth.login(request, user)
            return HttpResponseRedirect(reverse('testing:themes'))
    else:
        form = UserCreationForm()

    context = {
        'title': 'Регистрация',
        'form': form
    }
    return render(request, 'testing/signup.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('testing:themes'))
    else:
        form = AuthenticationForm()
    context = {
        'title': 'Авторизация',
        'form': form
    }
    return render(request, 'testing/login.html', context)


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('home'))


@login_required
def themes(request):
    themes = Theme.objects.all()
    context = {
        'title': 'Themes',
        'themes': themes
    }
    return render(request, 'testing/themes.html', context)


def tests(request, theme_pk):
    theme = Theme.objects.get(pk=theme_pk)
    tests = Test_single.objects.filter(theme=theme)

    # creates a dict for total number of questions for tests page (doesn't work - test_sizes.test.id doesn't work in django template)
    test_sizes = {}
    for test in tests:
        questions = Question.objects.filter(test=test)
        test_size = len(questions)
        test_sizes[test.id] = test_size

    context = {
        'title': 'Tests',
        'theme': theme,
        'tests': tests,
        'test_sizes': test_sizes,
        # 'number_of_questions': number_of_questions
    }
    return render(request, 'testing/tests.html', context)


def questions(request, test_pk, theme_pk, page=1):
    theme = Theme.objects.get(pk=theme_pk)
    test = Test_single.objects.filter(theme=theme).get(pk=test_pk)
    questions = Question.objects.filter(test=test)

    paginator = Paginator(questions, 1)
    questions_paginator = paginator.page(page)
    question = questions_paginator.object_list[0]  # first and only question for a page

    choices = Choice.objects.filter(question=question)
    answers = Answer.objects.filter(user=request.user, theme=theme, test=test, question=question)

    # just a list of answers id (need for displaying chosen choices and disabled send button after for submission
    answers_id = []
    for ans in answers:
        answers_id.append(ans.choice.id)

    context = {
        'title': test,
        'theme': theme,
        'test': test,
        'choices': choices,
        'page': page,
        'question': question,
        'answers_id': answers_id,
        'questions': questions,
        'questions_pag': questions_paginator,
    }

    if request.method == "POST":

        # creates a dicts list of current answers of user
        dicts = []
        answers_ids = request.POST.getlist('choice')  # gets ids of user answers
        for el in range(len(answers_ids)):
            dict = request.POST.copy()
            dict['choice'] = answers_ids[el]
            dicts.append(dict)

        # a custom form validation
        if len(answers_ids) == 0:
            context.update({'answer': AnswerForm(), 'error': 'Выберите хотя бы 1 вариант'})
            return render(request, 'testing/questions.html', context)
        elif len(answers_ids) == len(choices):
            context.update({'answer': AnswerForm(), 'error': 'Выбор всех значений недопустим'})
            return render(request, 'testing/questions.html', context)
        elif len(answers_ids) > question.max_points:
            context.update({'answer': AnswerForm(), 'error': f'Выберите {int(question.max_points)} значение/я', })
            return render(request, 'testing/questions.html', context)
        else:
            for dict in dicts:
                form = AnswerForm(dict)
                answer = form.save(commit=False)
                answer.user = request.user
                answer.theme = theme
                answer.test = test
                answer.question = question
                answer.save()
        return redirect(
            request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))  # refreshes a page after form submission

    context.update({
        'answers': answers,
    })
    return render(request, 'testing/questions.html', context)


def results(request, theme_pk, test_pk):
    user = request.user
    theme = Theme.objects.get(pk=theme_pk)
    test = Test_single.objects.filter(theme=theme).get(pk=test_pk)
    questions = Question.objects.filter(test=test)

    answers = Answer.objects.filter(user=user, test=test).select_related('choice').all()
    total_points = sum(answer.choice.points for answer in answers)  # displays number of scored points for a user
    max_points = sum(question.max_points for question in questions)  # displays max points for a test

    # point in percent
    total_points_percent = round(total_points / max_points * 100, 2)
    if total_points_percent == 100:
        total_points_percent = int(total_points_percent)
    max_points_percent = 100

    # saving results in DB (page doesn't created)
    result = Results(user=user, theme=theme, test=test, sum_points=total_points)
    result.save()

    context = {
        'title': 'Results',
        'theme': theme,
        'test': test,
        'total_points': total_points,
        'max_points': max_points,
        'total_points_percent': total_points_percent,
        'max_points_percent': max_points_percent,
    }
    return render(request, 'testing/results.html', context)

testing/templates/testing/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title|title}}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'testing/custom_styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success">
      <div class="container">
        <a class="navbar-brand text-white fs-3" href="{% url 'home' %}">TestService</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-row-reverse" id="navbarNav">

          <ul class="navbar-nav">
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-white fs-5" href="{% url 'login' %}">Войти</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link text-white fs-5" href="{% url 'testing:themes' %}">{{user.username}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white fs-5" href="{% url 'logout' %}">Выйти</a>
            </li>
            {% endif %}
          </ul>

        </div>
      </div>
    </nav>
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

testing/templates/testing/home.html
{% extends 'testing/base.html' %}

{% block content %}

<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="row justify-content-center mt-5">
    <div class="col-md-7 text-center">
        <h1>Добро пожаловать на портал онлайн-тестирования!</h1>
        <br>
        <p class="fs-5">Для прохождения тестов необходимо быть зарегистрированным. Тесты разбиты по темам.
            По окончанию тестов будет выведен результат.</p>
        <br>

        <button id="go-test" type="button" class="btn btn-lg btn-success">
            {% if user.is_authenticated %}
                <a id="go-test-link" class="text-white text-decoration-none text-reset" href="{% url 'testing:themes' %}">
                    Перейти к выбору тем</a>
            {% else %}
                <a id="go-test-link-not-auth" class="text-white text-decoration-none text-reset" href="{% url 'login' %}">
                    Перейти к выбору тем</a>
            {% endif %}
        </button>
    </div>
</div>

{% endblock %}

testing/templates/testing/login.html
{% extends 'testing/base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <h2 class="text-center">Авторизация</h2>
            {% if form.errors %}
            <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %}
                alert-dismissible fade show" role="alert" style="margin-top: 20px;">
                {% if form.non_field_errors%}
                    {{ form.non_field_errors }}
                {% else %}
                    {{ form.errors }}
                {% endif %}
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Логин</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group" style="margin-top: 10px;">
                    <label for="password">Пароль</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <br>
                <div class="text-center">
                    <button type="submit" class="btn btn-lg btn-secondary">Войти</button>
                    <br><hr>
                    <button class="btn btn-link fs-6" type="button">
                        <a href="{% url 'signup' %}">Еще нет аккаунта? Зарегистрироваться!</a></button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

testing/templates/testing/questions.html
{% extends 'testing/base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8">
            <h2>Тема: {{ theme }}</h2>
            <h3>Тест: {{ test }}</h3>
            <hr>

            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}

            <div>
                {% if question %}
                        <div class="fs-4">
                            <div class="">{{ question.title }}</div>
                            <div class="fs-5 text-muted">Максимум баллов: {{ question.max_points }}</div>
                        </div>
                {% else %}
                    Кажется, кто-то забыл добавить вопросы :(
                {% endif %}
            </div>

            <form id="myform" method="POST">
                {% csrf_token %}
                {% if not answers %}
                    {% for choice in choices %}
                        <div class="row">
                            <div class="col-md-1 text-center">
                                <input type="checkbox" name="choice" class="form-check-input fs-4" style="margin-top: 12px;" value="{{choice.id}}" id="choice">
                            </div>
                            <div class="col p-0">
                                <label class="form-check-label fs-4" for="choice" style="margin-top: 5px;">{{choice}}</label><br>
                            </div>
                        </div>
                    {% endfor %}
                    <br>
                    <div class="text-center">
                        <input type="submit" value="Отправить" class='btn btn-success' id="ob_submit">
                    </div>
                {% else %}
                    {% for choice in choices %}
                        {% if choice.id in answers_id %}
                        <div class="row">
                            <div class="col-md-1 text-center">
                                <input type="checkbox" name="choice" checked class="form-check-input fs-4" style="margin-top: 12px;" value="{{choice.id}}" >
                            </div>
                            <div class="col p-0">
                                <label class="form-check-label fs-4" for="choice" style="margin-top: 5px;">{{choice}}</label><br>
                            </div>
                        </div>
                        {% else %}
                        <div class="row">
                            <div class="col-md-1 text-center">
                                <input type="checkbox" name="choice" class="form-check-input fs-4" style="margin-top: 12px; " value="{{choice.id}}">
                            </div>
                            <div class="col p-0">
                                <label class="form-check-label fs-4" for="choice" style="margin-top: 5px;">{{choice}}</label><br>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                    <br>
                    <div class="text-center">
                        <button class='btn btn-success' disabled="disabled" type="submit">Отправить</button>
                    </div>
                {% endif %}
            </form>

            <br>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not questions_pag.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="{% if questions_pag.has_previous %}
                        {% url 'testing:page' theme.id test.id questions_pag.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">
                            Назад</a>
                    </li>

                    <li class="page-item disabled ">
                        <a class="page-link" href="#">
                            {{page}}/{{ questions|length }}</a>
                    </li>

                    <li class="page-item {% if not questions_pag.has_next or not answers %} disabled {% endif %}">
                        <a onclick="hide()" class="page-link" href="{% if questions_pag.has_next %}
                        {% url 'testing:page' theme.id test.id questions_pag.next_page_number %} {% else %} # {% endif %}">
                            Далее</a>
                    </li>
                </ul>
            </nav>

            <hr>

            {% if not questions_pag.has_next and not error and answers %}
            <div class="text-center">
                <a href="{% url 'testing:results' theme.id test.id %}"><button class="btn btn-lg btn-success">Завершить тест</button></a>
            </div>
            {% endif %}

        </div>
    </div>
</div>

<script>
    let m = document.getElementById('myform');

    function one() {
        m.submit();
        }

    function two() {
        document.getElementById('reloader').click();
        }

    function reload_interval(time){
        setTimeout(function(){
            location.reload();
        }, time);
    }
</script>
{% endblock %}

testing/templates/testing/results.html
{% extends 'testing/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8">
            <h2>Результаты</h2>
            <hr>
            <h3>Тема: {{ theme }}</h3>
            <h4>Тест: {{ test }}</h4>
            <br>
            <br>
            <br>
            <div class="text-center">
                <h1 class="text-center">Поздравляем!</h1><br>
                <h3>Вы набрали: {{total_points}}/{{max_points}}
                    <br><br>{{total_points_percent}}/{{max_points_percent}} %</h3>
            </div>
        </div>
    </div>
</div>
{% endblock %}

testing/templates/testing/signup.html
{% extends 'testing/base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <h2 class="text-center">Регистрация</h2>
            {% if form.errors %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert"
                    style="margin-top: 20px;">
                    {{form.errors}}
                    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            <div>
                <form action="{% url 'signup' %}" method = 'post'>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Логин</label>
                        <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                        <small id="usernameHelp" class="form-text text-muted">Ваш логин должен быть уникальным. Мы сообщим, если он уже занят.</small>
                    </div>
                    <div class="form-group" style="margin-top: 10px;">
                        <label for="password1">Пароль</label>
                        <input type="password" name="password1" class="form-control" id="password1">
                    </div>
                    <div class="form-group" style="margin-top: 10px;">
                        <label for="password2">Повторите пароль</label>
                        <input type="password" name="password2" class="form-control" id="password2">
                    </div>
                    <br>
                    <div class="text-center">
                        <button type="submit" class="btn btn-lg btn-secondary">Зарегистрироваться</button>
                        <br><hr>
                        <button class="btn btn-link fs-6" type="button">
                        <a href="{% url 'login' %}">Уже есть аккаунт? Войти!</a></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

testing/templates/testing/tests.html
{% extends 'testing/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8">
            <h2>Выберите тест</h2>
            <hr>
            <h3>Тема: {{theme}}</h3>
            <br>
            <div>
                {% for test in tests %}
                    <div class="row" style="margin-top: 10px;">
                        <div class="col">
                            <h4><a href="{% url 'testing:questions' theme.id test.id %}">{{ test.title }}</a></h4>
                        </div>
                        <div class="col text-end">
                            {{test_sizes.test.id}}
                        </div>
                    </div>
                {% empty %}
                    <p>Кажется, тесты по данной теме на данный момент отсутствуют:(</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

testing/templates/testing/themes.html
{% extends 'testing/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-8">
            {% if themes %}
                <h2>Выберите тему</h2>
                <hr>
                {% for theme in themes %}
                    <h4><a href="{% url 'testing:tests' theme.id %}">{{ theme.title }}</a></h4>
                    <p class="fs-5">{{ theme.description }}</p>
                {% endfor %}
            {% else %}
                <p>Кажется, темы на данный момент отсутствуют:(</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}